version: '3.7'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8009:80
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin
      WORDPRESS_DB_NAME: wpdata
    volumes:
      - type: bind
        source: ./volumes/wordpress
        target: /var/www/html

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: dbdata
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - type: bind
        source: ./volumes/dbdata
        target: /var/lib/mysql